---
- name: add keys for docker repository
  apt_key: 
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: add docker repository
  apt_repository: 
    repo: deb http://apt.dockerproject.org/repo ubuntu-xenial main
    state: present
    filename: 'docker'

- name: install docker
  apt: state=present name=docker-engine
