---
- name: add keys for dotnet repository
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80
    id:  417A0893

- name: add dotnet repository
  apt_repository: 
    repo: deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main
    state: present
    filename: 'dot-net'

- name: install dotnet
  apt: state=present name=dotnet-dev-1.0.4 
